[
    {
        "record": {
            "book_id": 6,
            "library_id": 5,
            "title": "father eat",
            "isbn": "1482544245063",
            "total_copies": 86,
            "publication_date": "2025-08-31",
            "available_copies": 48
        },
        "error": "1 validation error for Book\npublication_date\n  Value error, It's not possible to give the future date [type=value_error, input_value='2025-08-31', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.11/v/value_error"
    },
    {
        "record": {
            "book_id": 7,
            "library_id": 2,
            "title": "dog",
            "isbn": "5934147579042",
            "total_copies": 69,
            "publication_date": "2025-09-02",
            "available_copies": 20
        },
        "error": "1 validation error for Book\npublication_date\n  Value error, It's not possible to give the future date [type=value_error, input_value='2025-09-02', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.11/v/value_error"
    },
    {
        "record": {
            "book_id": 9,
            "library_id": 1,
            "title": "politics",
            "isbn": "bad-isbn",
            "total_copies": 57,
            "publication_date": "2023-09-15",
            "available_copies": 22
        },
        "error": "1 validation error for Book\nisbn\n  Value error, ISBN must be 10 or 13 digits [type=value_error, input_value='bad-isbn', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.11/v/value_error"
    },
    {
        "record": {
            "book_id": 10,
            "library_id": -1,
            "title": "yourself right",
            "isbn": "5091159879",
            "total_copies": 75,
            "publication_date": "2012-12-03",
            "available_copies": 3
        },
        "error": "exceptions must derive from BaseException"
    },
    {
        "record": {
            "book_id": 14,
            "library_id": 1,
            "title": "skill wall create",
            "isbn": "3802562226",
            "total_copies": 63,
            "publication_date": "2025-10-05",
            "available_copies": 5
        },
        "error": "1 validation error for Book\npublication_date\n  Value error, It's not possible to give the future date [type=value_error, input_value='2025-10-05', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.11/v/value_error"
    },
    {
        "record": {
            "book_id": 15,
            "library_id": 5,
            "title": "hotel unit",
            "isbn": "1091873684326",
            "total_copies": 53,
            "publication_date": "2012-01-04",
            "available_copies": 0
        },
        "error": "1 validation error for Book\navailable_copies\n  Value error, Available copies won't be less than 0 [type=value_error, input_value=0, input_type=int]\n    For further information visit https://errors.pydantic.dev/2.11/v/value_error"
    },
    {
        "record": {
            "book_id": -18,
            "library_id": 3,
            "title": "democratic safe read",
            "isbn": "8344697044411",
            "total_copies": 63,
            "publication_date": "2024-07-28",
            "available_copies": 48
        },
        "error": "1 validation error for Book\nbook_id\n  Value error, Book id cannot be negative [type=value_error, input_value=-18, input_type=int]\n    For further information visit https://errors.pydantic.dev/2.11/v/value_error"
    },
    {
        "record": {
            "book_id": 19,
            "library_id": -1,
            "title": "cold accept",
            "isbn": "4812224333713",
            "total_copies": 75,
            "publication_date": "2022-07-09",
            "available_copies": 0
        },
        "error": "exceptions must derive from BaseException"
    },
    {
        "record": {
            "book_id": -22,
            "library_id": 3,
            "title": "later candidate partner adult",
            "isbn": "7667827319",
            "total_copies": 48,
            "publication_date": "2017-01-02",
            "available_copies": 21
        },
        "error": "1 validation error for Book\nbook_id\n  Value error, Book id cannot be negative [type=value_error, input_value=-22, input_type=int]\n    For further information visit https://errors.pydantic.dev/2.11/v/value_error"
    },
    {
        "record": {
            "book_id": 23,
            "library_id": 4,
            "title": "expert forget simple safe",
            "isbn": "bad-isbn",
            "total_copies": 49,
            "publication_date": "2019-06-08",
            "available_copies": 13
        },
        "error": "1 validation error for Book\nisbn\n  Value error, ISBN must be 10 or 13 digits [type=value_error, input_value='bad-isbn', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.11/v/value_error"
    },
    {
        "record": {
            "book_id": 25,
            "library_id": 2,
            "title": "short heart catch family",
            "isbn": "2186095878",
            "total_copies": 7,
            "publication_date": "2016-05-01",
            "available_copies": 0
        },
        "error": "1 validation error for Book\navailable_copies\n  Value error, Available copies won't be less than 0 [type=value_error, input_value=0, input_type=int]\n    For further information visit https://errors.pydantic.dev/2.11/v/value_error"
    },
    {
        "record": {
            "book_id": 30,
            "library_id": 1,
            "title": "beautiful",
            "isbn": "8086002336",
            "total_copies": 94,
            "publication_date": "2025-10-01",
            "available_copies": 50
        },
        "error": "1 validation error for Book\npublication_date\n  Value error, It's not possible to give the future date [type=value_error, input_value='2025-10-01', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.11/v/value_error"
    },
    {
        "record": {
            "book_id": 33,
            "library_id": 5,
            "title": "wish range son",
            "isbn": "8334751339019",
            "total_copies": 95,
            "publication_date": "2021-12-10",
            "available_copies": 0
        },
        "error": "1 validation error for Book\navailable_copies\n  Value error, Available copies won't be less than 0 [type=value_error, input_value=0, input_type=int]\n    For further information visit https://errors.pydantic.dev/2.11/v/value_error"
    },
    {
        "record": {
            "book_id": -34,
            "library_id": 4,
            "title": "tv green your enter",
            "isbn": "1236832643",
            "total_copies": 49,
            "publication_date": "2025-08-20",
            "available_copies": 46
        },
        "error": "2 validation errors for Book\nbook_id\n  Value error, Book id cannot be negative [type=value_error, input_value=-34, input_type=int]\n    For further information visit https://errors.pydantic.dev/2.11/v/value_error\npublication_date\n  Value error, It's not possible to give the future date [type=value_error, input_value='2025-08-20', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.11/v/value_error"
    },
    {
        "record": {
            "book_id": 35,
            "library_id": -1,
            "title": "mouth",
            "isbn": "0738382140018",
            "total_copies": 38,
            "publication_date": "2024-06-04",
            "available_copies": 0
        },
        "error": "exceptions must derive from BaseException"
    },
    {
        "record": {
            "book_id": -37,
            "library_id": 5,
            "title": "event",
            "isbn": "0010115955655",
            "total_copies": 85,
            "publication_date": "2022-05-30",
            "available_copies": 18
        },
        "error": "1 validation error for Book\nbook_id\n  Value error, Book id cannot be negative [type=value_error, input_value=-37, input_type=int]\n    For further information visit https://errors.pydantic.dev/2.11/v/value_error"
    },
    {
        "record": {
            "book_id": 38,
            "library_id": -1,
            "title": "north throw dark reason",
            "isbn": "3196315192",
            "total_copies": 61,
            "publication_date": "2012-07-02",
            "available_copies": 9
        },
        "error": "exceptions must derive from BaseException"
    },
    {
        "record": {
            "book_id": -44,
            "library_id": 5,
            "title": "land gun option",
            "isbn": "bad-isbn",
            "total_copies": 67,
            "publication_date": "2014-09-28",
            "available_copies": 25
        },
        "error": "2 validation errors for Book\nbook_id\n  Value error, Book id cannot be negative [type=value_error, input_value=-44, input_type=int]\n    For further information visit https://errors.pydantic.dev/2.11/v/value_error\nisbn\n  Value error, ISBN must be 10 or 13 digits [type=value_error, input_value='bad-isbn', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.11/v/value_error"
    },
    {
        "record": {
            "book_id": 45,
            "library_id": 5,
            "title": "happy",
            "isbn": "5135856126",
            "total_copies": 85,
            "publication_date": "2025-08-09",
            "available_copies": 28
        },
        "error": "1 validation error for Book\npublication_date\n  Value error, It's not possible to give the future date [type=value_error, input_value='2025-08-09', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.11/v/value_error"
    },
    {
        "record": {
            "book_id": -46,
            "library_id": 2,
            "title": "Behavior   ",
            "isbn": "3665559335",
            "total_copies": 46,
            "publication_date": "2020-10-01",
            "available_copies": 27
        },
        "error": "1 validation error for Book\nbook_id\n  Value error, Book id cannot be negative [type=value_error, input_value=-46, input_type=int]\n    For further information visit https://errors.pydantic.dev/2.11/v/value_error"
    },
    {
        "record": {
            "book_id": 49,
            "library_id": -1,
            "title": "find",
            "isbn": "6467661390031",
            "total_copies": 68,
            "publication_date": "2011-12-20",
            "available_copies": 0
        },
        "error": "exceptions must derive from BaseException"
    },
    {
        "record": {
            "book_id": -50,
            "library_id": 4,
            "title": "sister",
            "isbn": "7405382979",
            "total_copies": 46,
            "publication_date": "2016-01-30",
            "available_copies": 0
        },
        "error": "2 validation errors for Book\nbook_id\n  Value error, Book id cannot be negative [type=value_error, input_value=-50, input_type=int]\n    For further information visit https://errors.pydantic.dev/2.11/v/value_error\navailable_copies\n  Value error, Available copies won't be less than 0 [type=value_error, input_value=0, input_type=int]\n    For further information visit https://errors.pydantic.dev/2.11/v/value_error"
    }
]